version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    depends_on:
      - kafka
    ports:
      - "50081:50081"
    environment:
      - PRODUCT_SERVICE_PORT=50081
      - KAFKA_BROKER=kafka:29092
      - USE_REAL_KAFKA=true

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    depends_on:
      - kafka
      - product-service
    ports:
      - "50082:50082"
    environment:
      - ORDER_SERVICE_PORT=50082
      - PRODUCT_SERVICE_ADDR=product-service:50081
      - KAFKA_BROKER=kafka:29092
      - USE_REAL_KAFKA=true

  customer-service:
    build:
      context: .
      dockerfile: customer-service/Dockerfile
    container_name: customer-service
    depends_on:
      - kafka
    ports:
      - "50083:50083"
    environment:
      - CUSTOMER_SERVICE_PORT=50083
      - KAFKA_BROKER=kafka:29092
      - USE_REAL_KAFKA=true

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - product-service
      - order-service
      - customer-service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - PRODUCT_SERVICE_ADDR=product-service:50081
      - ORDER_SERVICE_ADDR=order-service:50082
      - CUSTOMER_SERVICE_ADDR=customer-service:50083
